run-name: Deploy astarlogic.com

on:
  push:
    branches: [main]
    paths:
      - 'ansearch/**'

  # Allow manual trigger
  workflow_dispatch:

jobs:
  Deploy:
    runs-on: ubuntu-latest
    name: deploy website
    environment: production
    steps:
      - uses: actions/checkout@v4

      - name: Prepare
        uses: ./.github/actions/prepare

      - name: Build
        run: yarn workspace ansearch build

      - name: Deploy
        run: yarn workspace ansearch deploy
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
        shell: bash
